#!/usr/bin/env python3
"""
frsr_mp_hook.py — Minimal CPL-only helper for MontePython.

Purpose:
  • Emit a tiny .param that sets CLASS CPL fluid: w0_fld, wa_fld, cs2_fld=1.0, use_ppf='yes', Omega_Lambda=0.0.
  • Optionally map (kernel knobs) → (w0, wa) using the single-source function in frsr.core.frsr_background.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Optional, Sequence, Tuple

# Keep FRSR physics single-sourced in frsr_background:
try:
    # Installed module path: frsr_calibrate/src is usually on PYTHONPATH as frsr.core
    from frsr.core.frsr_background import Kernel, SpectralKnobs, map_kernel_to_cpl
except Exception as _imp_err:
    map_kernel_to_cpl = None
    SpectralKnobs = None
    Kernel = None


# -----------------------
# MontePython .param writer
# -----------------------
def write_minimal_param(
    out_path: str,
    *,
    h: float,
    omega_b: float,
    omega_cdm: float,
    w0: float = -1.0,
    wa: float = 0.0,
    experiments: Optional[list] = None,
    nuisance_lines: Optional[list] = None,
) -> str:
    """
    Write a minimal MontePython .param using data.cosmo_arguments[...] assignments.
    Sets:
      Omega_Lambda=0.0, use_ppf='yes', cs2_fld=1.0, w0_fld, wa_fld, and basic Ω/h inputs.
    """
    experiments = experiments or []
    p = Path(out_path)
    p.parent.mkdir(parents=True, exist_ok=True)

    lines = []
    lines.append("# Auto-generated by frsr_mp_hook.write_minimal_param\n")
    lines.append("data.experiments = %r\n" % experiments)
    lines.append("\n")

    # --- Primordial & reionization (Planck requires these) ---
    lines.append("data.parameters['A_s']      = [2.10e-9, 1.50e-9, 3.50e-9, 1.0e-11, 1, 'cosmo']\n")
    lines.append("data.parameters['n_s']      = [0.965,   0.90,    1.02,    0.001,   1, 'cosmo']\n")
    lines.append("data.parameters['tau_reio'] = [0.060,   0.01,    0.15,    0.002,   1, 'cosmo']\n")
    lines.append("\n")

    # --- H0 sampling (keep visible like the successful template) ---
    H0_val = 100.0 * float(h)
    lines.append("data.parameters['H0']       = [%.3f,    50.0,    80.0,    0.2,     1, 'cosmo']\n" % H0_val)
    lines.append("\n")

    # --- CPL dark energy (seed from provided w0/wa but keep as parameters) ---
    lines.append("data.parameters['w0_fld']   = [%.12g,  -1.50,   -0.70,    0.01,    1, 'cosmo']\n" % w0)
    lines.append("data.parameters['wa_fld']   = [%.12g,   -0.60,    0.30,    0.01,    1, 'cosmo']\n" % wa)
    lines.append("\n")

    # --- SNe/CMB nuisances (only if passed) ---
    if nuisance_lines is not None and len(nuisance_lines) > 0:
        lines.extend(nuisance_lines)
    lines.append("\n")

    # --- Fixed CLASS background pieces (match previous working style) ---
    lines.append("data.cosmo_arguments['use_ppf']      = 'yes'\n")
    lines.append("data.cosmo_arguments['cs2_fld']      = 1.0\n")
    lines.append("data.cosmo_arguments['omega_b']      = %s\n" % omega_b)
    lines.append("data.cosmo_arguments['omega_cdm']    = %s\n" % omega_cdm)
    lines.append("data.cosmo_arguments['Omega_k']      = 0.0\n")
    lines.append("data.cosmo_arguments['Omega_Lambda'] = 0.0\n")
    lines.append("\n")

    # --- Ensure CLASS computes lensed Cl for Planck high-ell ---
    lines.append("data.cosmo_arguments['lensing'] = 'yes'\n")
    lines.append("data.cosmo_arguments['output']  = 'tCl pCl lCl'\n")
    lines.append("data.cosmo_arguments['l_max_scalars'] = 3000\n")
    p.write_text("".join(lines))
    return str(p)


# -----------------------
# CLI
# -----------------------
def _build_cli() -> argparse.ArgumentParser:
    ap = argparse.ArgumentParser(description="FRSR MontePython utilities")
    sub = ap.add_subparsers(dest="cmd")

    # Only the minimal make-param CLI is supported now
    sp3 = sub.add_parser(
        "make-param",
        help="Generate MontePython .param. If --w0/--wa not provided but --epsilon/--alpha are, maps them to CPL.",
    )
    sp3.add_argument("--out", required=True, help="Path to write frsr.param")
    sp3.add_argument("--h", type=float, required=True)
    sp3.add_argument("--omega-b", type=float, required=True)
    sp3.add_argument("--omega-cdm", type=float, required=True)
    sp3.add_argument("--w0", type=float, default=None)
    sp3.add_argument("--wa", type=float, default=None)
    sp3.add_argument(
        "--experiments",
        type=str,
        default="",
        help="Comma-separated list, e.g. Planck_highl_TTTEEE_lite,Planck_lensing,bao_boss_dr12,Pantheon,hst",
    )
    # Kernel-related arguments
    sp3.add_argument("--kernel", type=str, default="power2", help="Spectral kernel: 'power2' (default) or 'exp'")
    sp3.add_argument("--xi", type=float, default=0.3, help="Macro decay timescale for EXP kernel (default 0.3)")
    sp3.add_argument("--s0", type=float, default=0.3, help="Turnover scale for POWER2 kernel (default 0.3)")
    sp3.add_argument("--sc", type=float, default=0.0, help="Optional micro-coherence scale")
    # Nuisance parameters
    sp3.add_argument("--a-planck-start", type=float, default=None)
    sp3.add_argument("--a-planck-min", type=float, default=None)
    sp3.add_argument("--a-planck-max", type=float, default=None)
    sp3.add_argument("--a-planck-step", type=float, default=None)
    sp3.add_argument("--M-start", type=float, default=None)
    sp3.add_argument("--M-min", type=float, default=None)
    sp3.add_argument("--M-max", type=float, default=None)
    sp3.add_argument("--M-step", type=float, default=None)
    # Remove legacy epsilon/alpha from CLI
    return ap


def _main(argv: Optional[Sequence[str]] = None) -> int:
    argv = list(argv) if argv is not None else sys.argv[1:]
    if argv and argv[0] == "--make-param":
        argv = ["make-param", *argv[1:]]

    ap = _build_cli()
    args = ap.parse_args(argv)
    if args.cmd is None:
        ap.print_help()
        return 2

    if args.cmd == "make-param":
        exps = [s.strip() for s in (args.experiments or "").split(",") if s.strip()]
        w0 = args.w0
        wa = args.wa

        # Priority: kernel → CPL (v2.1 default), then fallback to LCDM
        if w0 is None or wa is None:
            if map_kernel_to_cpl is None:
                raise RuntimeError("FRSR core mapping not available (map_kernel_to_cpl).")
            # Build spectral knob object
            kname = (args.kernel or "power2").strip().lower()
            if kname in ("power2", "power", "pow2"):
                spec = SpectralKnobs(kernel=Kernel.POWER2, s0=args.s0 or 0.3, sc=args.sc or 0.0)
            elif kname in ("exp", "exponential"):
                spec = SpectralKnobs(kernel=Kernel.EXP, xi=args.xi or 0.3, sc=args.sc or 0.0)
            else:
                raise ValueError(f"Unknown kernel: {args.kernel}")
            w0, wa = map_kernel_to_cpl(spec)
        if w0 is None or wa is None:
            # Default to LCDM if nothing specified
            w0, wa = -1.0, 0.0

        nuis = []
        if (
            args.a_planck_start is not None
            and args.a_planck_min is not None
            and args.a_planck_max is not None
            and args.a_planck_step is not None
        ):
            nuis.append(
                f"data.parameters['A_planck'] = [{args.a_planck_start}, {args.a_planck_min}, {args.a_planck_max}, {args.a_planck_step}, 1, 'nuisance']\n"
            )
        if args.M_start is not None and args.M_min is not None and args.M_max is not None and args.M_step is not None:
            nuis.append(
                f"data.parameters['M'] = [{args.M_start}, {args.M_min}, {args.M_max}, {args.M_step}, 1, 'nuisance']\n"
            )

        path = write_minimal_param(
            args.out,
            h=args.h,
            omega_b=args.omega_b,
            omega_cdm=args.omega_cdm,
            w0=w0,
            wa=wa,
            experiments=exps,
            nuisance_lines=nuis,
        )
        print(path)
        return 0

    ap.print_help()
    return 2


if __name__ == "__main__":
    # Keep legacy entrypoints working if any; otherwise expose the small CLI above
    try:
        sys.exit(_main())
    except Exception as e:
        print(f"[frsr_hook] error: {e}")
        raise
