# -*- coding: utf-8 -*-
# Copyright (C) 2025 Sangwook Lee @ Plusgenie Limited
# This file is part of FRSR (Finite Residual Rule of Sum) under GPLv3+.
#
# CLI: Generate a minimal CLASS background .ini (CPL mode only; no w-table).
# - Reads Omega_de0 from params.json (preferred: ["class_params"]["Omega_de0"])
# - Falls back to --defaults value if not present and --defaults is set
# - Writes frsr_background.ini into the run directory
# - Uses frsr.utils.log for consistent logging
#
# Example:
#   python -m frsr.cli.run_calibrate \
#       --run-dir runs/calibrate/demo \
#       --params runs/calibrate/demo/params.json \
#       --defaults 0.68 \
#       --w0 -0.98 --wa 0.0

from __future__ import annotations

import argparse
import json
import os
from datetime import datetime
from typing import Any, Dict, Optional

from frsr.utils.log import init_logging, get_logger
from frsr.io.frsr_export_cpl import patch_class_root


# --------- helpers ---------

def _write_cpl_background_ini(out_path: str, *, Omega_fld: float, w0: float = -0.98, wa: float = 0.0) -> None:
    """
    Minimal CLASS background ini using CPL (no w_table).
    """
    lines = [
        "# Auto-generated by run_calibrate (CPL mode: no w_table)\n",
        "[background]\n",
        "Omega_Lambda = 0\n",
        f"Omega_fld = {Omega_fld:.10g}\n",
        "use_ppf = yes\n",
        "cs2_fld = 1\n",
        f"w0_fld = {w0:.10g}\n",
        f"wa_fld = {wa:.10g}\n",
        "",
        "# Outputs\n",
        "write parameters = yes\n",
        "write background = yes\n",
        "",
    ]
    os.makedirs(os.path.dirname(os.path.abspath(out_path)), exist_ok=True)
    with open(out_path, "w") as f:
        f.writelines(lines)


def _extract_Omega_de0(params_json_path: str) -> Optional[float]:
    """
    Try to read Omega_de0 from params.json written by FRSR stages.

    Preferred path:
        data["class_params"]["Omega_de0"]

    Legacy fallback:
        data["Omega_de0"]
    """
    try:
        if os.path.isfile(params_json_path):
            with open(params_json_path, "r") as f:
                data: Dict[str, Any] = json.load(f)
            if isinstance(data, dict):
                cls = data.get("class_params") or {}
                if isinstance(cls, dict) and "Omega_de0" in cls:
                    return float(cls["Omega_de0"])
                if "Omega_de0" in data:
                    return float(data["Omega_de0"])
    except Exception:
        pass
    return None


def _parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(
        description="Generate CLASS background .ini in CPL mode (no tabulated w)."
    )
    p.add_argument(
        "--run-dir",
        default=None,
        help="Directory for outputs (default: runs/calibrate/YYYYmmdd_HHMMSS).",
    )
    p.add_argument(
        "--params",
        default=None,
        help="Path to params.json (default: <run-dir>/params.json if exists).",
    )
    p.add_argument(
        "--defaults",
        type=float,
        default=None,
        help="If set, use this Omega_de0 when params.json lacks it (e.g., 0.68).",
    )
    p.add_argument("--w0", type=float, default=-0.98, help="CPL w0_fld (default: -0.98).")
    p.add_argument("--wa", type=float, default=0.0, help="CPL wa_fld (default: 0.0).")
    p.add_argument("--log-level", default=None, help="Override log level (DEBUG, INFO, ...).")
    return p.parse_args()


# --------- entrypoint ---------

def main() -> None:
    args = _parse_args()
    init_logging(level=args.log_level)
    log = get_logger()

    # Resolve run directory
    if args.run_dir:
        run_dir = os.path.abspath(args.run_dir)
    else:
        ts = datetime.now().strftime("%Y%m%d_%H%M%S")
        run_dir = os.path.abspath(os.path.join("runs", "calibrate", ts))
    os.makedirs(run_dir, exist_ok=True)
    log.info("Run directory: {}", run_dir)

    # Resolve params.json path
    params_json_path = os.path.abspath(args.params) if args.params else os.path.join(run_dir, "params.json")
    log.info("Params JSON: {}", params_json_path if os.path.exists(params_json_path) else "(missing)")

    # Extract Omega_de0
    Omega_de0: Optional[float] = _extract_Omega_de0(params_json_path)
    if Omega_de0 is None:
        if args.defaults is not None:
            Omega_de0 = float(args.defaults)
            log.warning("Omega_de0 not found in params.json; using default {}", Omega_de0)
        else:
            log.error("Omega_de0 missing and --defaults not provided. Aborting.")
            raise SystemExit(2)

    # Compose and write background ini
    bg_out = os.path.join(run_dir, "frsr_background.ini")
    _write_cpl_background_ini(bg_out, Omega_fld=Omega_de0, w0=args.w0, wa=args.wa)
    log.success("Wrote CPL background .ini: {}", bg_out)
    log.info("CPL parameters: w0_fld={}, wa_fld={}", args.w0, args.wa)
    log.info("Omega_fld (from Omega_de0) = {}", Omega_de0)

    # Optionally patch CLASS output root in the ini
    try:
        patch_class_root(bg_out, run_dir)
        log.debug("Patched CLASS output root in {}", bg_out)
    except Exception as e:
        log.debug("patch_class_root no-op or failed benignly: {}", e)

    log.success("Mode: CPL analytic dark energy")
    log.info("Done.")

if __name__ == "__main__":
    main()
