# -*- coding: utf-8 -*-

# Copyright (C) 2025 Sangwook Lee @ Plusgenie Limited
# This file is part of FRSR (Finite Residual Rule of Sum).
#
# FRSR is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# FRSR is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with FRSR.  If not, see <https://www.gnu.org/licenses/>.

# Author: Sangwook Lee (aladdin@plusgenie.com)
# Date: 2025-10-27

"""
SymPy / LaTeX reporting helpers.

This module centralizes all symbolic and LaTeX generation routines for FRSR
runs. It is used by both `run_calibrate.py` and `run_scan.py`.

Features
--------
- Symbolic definitions of q, S_N, and 𝓒_FRSR.
- Numeric evaluation (q, S_N, 𝓒_FRSR, front).
- Console pretty-print report.
- Optional LaTeX export to <run_dir>/symbolic.tex or user-specified path.
"""

from __future__ import annotations
import os
import sys
from typing import Optional


def emit_symbolic_report(
    run_dir: str,
    *,
    N_val: int,
    r_val: float,
    alpha_val: float,
    beta_val: float,
    kIR_val: float,
    E0_val: float,
    C_FRSR_val: float,
    q_val: float,
    latex_out_path: Optional[str] = None,
) -> None:
    """Generate a symbolic summary and LaTeX export for the FRSR ladder."""
    try:
        import sympy as sp
    except Exception as e:
        print(f"[warn] SymPy not available: {e}. Skipping symbolic report.", file=sys.stderr)
        return

    # ------------------------------------------------------------------
    # 1. Symbolic definitions
    # ------------------------------------------------------------------
    E0, alpha, kIR, r, beta, N = sp.symbols("E0 alpha k_IR r beta N", positive=True, real=True)
    q = r**4 * sp.exp(-beta)
    S_N = (1 - q**N) / (1 - q)  # finite geometric sum
    Csym = E0 * alpha * kIR**4 * S_N
    front = E0 * alpha * kIR**4

    # ------------------------------------------------------------------
    # 2. Numeric evaluation
    # ------------------------------------------------------------------
    subs_map = {
        E0: E0_val,
        alpha: alpha_val,
        kIR: kIR_val,
        r: r_val,
        beta: beta_val,
        N: int(N_val),
    }
    q_num = float(sp.N(q.subs(subs_map)))
    S_N_num = float(sp.N(S_N.subs(subs_map)))
    C_num = float(sp.N(Csym.subs(subs_map)))
    front_num = float(sp.N(front.subs(subs_map)))

    # ------------------------------------------------------------------
    # 3. Console report
    # ------------------------------------------------------------------
    print("\n[symbolic]")
    print(f"model=exp  (Finite sum with N={N_val}.)")
    print(f"q (convergence factor) = {q_num:.6f}")
    if q_num < 1.0:
        print("criterion (|q|<1 for N→∞) -> satisfied for infinite series; here N is finite.")
    else:
        print("criterion (|q|<1 for N→∞) -> not satisfied; using finite N sum (safe).")
    print(f"𝓒_FRSR (closed form)   = {C_num:.6e}  (m^-4)")
    print(f"front = E0·α·k_IR⁴     = {front_num:.6e}")
    print(f"S_N (finite)           = {S_N_num:.6e}")

    # ------------------------------------------------------------------
    # 4. LaTeX export
    # ------------------------------------------------------------------
    try:
        latex_lines = [
            r"% Auto-generated by frsr.cli.sympy_report.emit_symbolic_report",
            r"\[ q = r^{4} e^{-\beta} \]",
            r"\[ S_N = \frac{1 - q^{N}}{1 - q} \]",
            r"\[ \mathcal{C}_{\mathrm{FRSR}} = E_{0}\,\alpha\,k_{\mathrm{IR}}^{4}\,S_N \]",
            r"\[ \mathcal{C}_{\mathrm{FRSR}} = "
            + sp.latex(sp.simplify(Csym))
            + r" \]",
            r"\[ \text{front} = " + sp.latex(front) + r" \]",
        ]
        latex_str = "\n".join(latex_lines)
        if latex_out_path is None:
            latex_out_path = os.path.join(run_dir, "symbolic.tex")
        os.makedirs(os.path.dirname(latex_out_path), exist_ok=True)
        with open(latex_out_path, "w") as f:
            f.write(latex_str + "\n")
        print(f"[ok] LaTeX exported: {latex_out_path}")
    except Exception as e:
        print(f"[warn] Could not export LaTeX: {e}", file=sys.stderr)
